# config/config.yml

production:
  #Messaging service selector 
  #yammer or jabber
  # @Examples service: yammer   or service: jabber
  service: jabber

  # Array of email addresses separated by comma when
  # use jabber as a service
  jabber_recipients: "devs@conference.bedsideclinicalsystems.com"
  jabber_sender: "codebot@bedsideclinicalsystems.com"
  jabber_sender_password: "codebot"
  jabber_alias: "devsbot"
